# OrangeHrm_locator python file to keep all xpath at one location"

class Locators:
    username = "username"
    password = "password"
    login = "//button[@type='submit']"
    pim = "//span[@class='oxd-text oxd-text--span oxd-main-menu-item--name' and text()='PIM']"
    forgot_link = "//p[text()='Forgot your password? ']"
    username_forgot = "//input[@name='username']"
    Reset_password = "//button[@type='submit' and text()=' Reset Password ']"
    reset_msg = "//h6[text()='Reset Password link sent successfully']"
    admin = "//span[text()='Admin']"
    user_management = "//span[text()='User Management ']"
    Job = "//span[text()='Job ']"
    Organization = "//span[text()='Organization ']"
    qualify = "//span[text()='Qualifications ']"
    Nationality_link = ("//div//header//div//nav//ul//li[5]//a[@class='oxd-topbar-body-nav-tab-item' and text("
                        ")='Nationalities']")
    corporate_bank = "//a[text()='Corporate Branding']"
    configuration = "//span[text()='Configuration ']"
    leave = "//span[text()='Leave']"
    Time = "//span[text()='Time']"
    recruitment = "//span[text()='Recruitment']"
    my_info = "//span[text()='My Info']"
    performance = "//span[text()='Performance']"
    dashboard = "//span[text()='Dashboard']"
    directory = "//span[text()='Directory']"
    maintenance = "//span[text()='Maintenance']"
    claim = "//span[text()='Claim']"
    buzz = "//span[text()='Buzz']"
